### ISSUE TITLE
有关于 `.PhotoView__PhotoWrap .PhotoView__PhotoBox`

### ISSUE THREAD

**Issue by d1y** [NameWjp/vue3-photo-preview#9]
没很仔细的去看源码, 只想简单使用一下

这个样式写死了 `w: 0`, 是否可以抽离出一个 `props`, 让用户传递?
(也有可能是我操作问题?搞了一个上午图片modal里图片一直不显示, 将 `w` 设置一个值之后就好了)

```css
.PhotoView__PhotoWrap .PhotoView__PhotoBox {
    width: 0;
    height: 0;
    display: flex;
    justify-content: center;
    align-items: center;
}
```
